version:  "3"
services:
  node-app:
    build: 
      context: .
      target: development
    volumes:
      # - type: bind
      #   source: ./src
      #   target: /app/src
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=development
    command: npm run start-dev
